enum LegislationRegisterErrorCode {
  LEGISLATION_REGISTER_NOT_FOUND = "LEGISLATION_REGISTER_NOT_FOUND",
  LEGISLATION_REGISTER_ALREADY_EXISTS = "LEGISLATION_REGISTER_ALREADY_EXISTS",
}

export default LegislationRegisterErrorCode;
