enum ClientDocumentTypeErrorCode {
  CLIENT_DOCUMENT_TYPE_NOT_FOUND = "DOCUMENT_TYPE_NOT_FOUND",
  CLIENT_DOCUMENT_TYPE_ALREADY_EXISTS = "DOCUMENT_TYPE_ALREADY_EXISTS",
}

export default ClientDocumentTypeErrorCode;
