enum StaffDocumentCategoryErrorCode {
  STAFF_DOCUMENT_CATEGORY_NOT_FOUND = "STAFF_DOCUMENT_CATEGORY_NOT_FOUND",
  CATEGORY_ALREADY_EXISTS = "CATEGORY_ALREADY_EXISTS",
  CATEGORY_CONTAINS_DUPLICATE_TYPE = "Category contains duplicate document",
  DOCUMENT_CATEGORY_IN_USE = "DOCUMENT_CATEGORY_IN_USE",
}

export default StaffDocumentCategoryErrorCode;
