enum ClientDocumentCategoryErrorCode {
  CATEGORY_NOT_FOUND = "CATEGORY_NOT_FOUND",
  CATEGORY_ALREADY_EXISTS = "CATEGORY_ALREADY_EXISTS",
  CATEGORY_CONTAINS_DUPLICATE_TYPE = "CATEGORY_CONTAINS_DUPLICATE_TYPE",
}

export default ClientDocumentCategoryErrorCode;
