import express from "express";

import authMiddleware from "../components/auth";
import { userRoutes } from "../api/user";
import { roleRoutes } from "../api/role";
import { companyRoutes } from "../api/company";
import { clientProfileRoutes } from "../api/clientProfile";
import { staffProfileRoutes } from "../api/staffProfile";
import { progressNoteRoutes } from "../api/progressNote";
import { bloodGlucoseLogRoutes } from "../api/bloodGlucoseLog";
import { bloodPressureLogRoutes } from "../api/bloodPressureLog";
import { bowelLogRoutes } from "../api/bowelLog";
import { weightLogRoutes } from "../api/weightLog";
import { sleepLogRoutes } from "../api/sleepLog";
import { temperatureLogRoutes } from "../api/temperatureLog";
import { prnAdminLogRoutes } from "../api/prnAdminLog";
import { prnBalanceLogRoutes } from "../api/prnBalanceLog";
import { oxygenSaturationLogRoutes } from "../api/oxygenSaturationLog";
import { seizureLogRoutes } from "../api/seizureLog";
import { clientBehaviourRoutes } from "../api/clientBehaviour";
import { transportBehaviourRoutes } from "../api/transportBehaviour";
import { vehicleLogRoutes } from "../api/vehicleLog";
import { injuryReportRoutes } from "../api/injuryReport";
import { expenseReimbursementRoutes } from "../api/expenseReimbursement";
import { doctorVisitRoutes } from "../api/doctorVisit";
import { clientAssetRoutes } from "../api/clientAsset";
import { companyAssetRoutes } from "../api/companyAsset";
import { repairRequestRoutes } from "../api/repairRequest";
import { conflictOfInterestRoutes } from "../api/conflictOfInterest";
import { corporateRiskRoutes } from "../api/corporateRisk";
import { clientRiskRoutes } from "../api/clientRisk";
import { staffSleepDisturbanceRoutes } from "../api/staffSleepDisturbance";

const router = express.Router();
router.use(authMiddleware);

router.use("/user", userRoutes);
router.use("/role", roleRoutes);
router.use("/company", companyRoutes);
router.use("/client-profile", clientProfileRoutes);
router.use("/staff-profile", staffProfileRoutes);
router.use("/progress-note", progressNoteRoutes);
router.use("/blood-glucose-log", bloodGlucoseLogRoutes);
router.use("/blood-pressure-log", bloodPressureLogRoutes);
router.use("/bowel-log", bowelLogRoutes);
router.use("/weight-log", weightLogRoutes);
router.use("/sleep-log", sleepLogRoutes);
router.use("/temperature-log", temperatureLogRoutes);
router.use("/prn-admin-log", prnAdminLogRoutes);
router.use("/prn-balance-log", prnBalanceLogRoutes);
router.use("/oxygen-saturation-log", oxygenSaturationLogRoutes);
router.use("/seizure-log", seizureLogRoutes);
router.use("/client-behaviour", clientBehaviourRoutes);
router.use("/transport-behaviour", transportBehaviourRoutes);
router.use("/vehicle-log", vehicleLogRoutes);
router.use("/injury-report", injuryReportRoutes);
router.use("/expense-reimbursement", expenseReimbursementRoutes);
router.use("/doctor-visit", doctorVisitRoutes);
router.use("/client-asset", clientAssetRoutes);
router.use("/company-asset", companyAssetRoutes);
router.use("/repair-request", repairRequestRoutes);
router.use("/conflict-of-interest", conflictOfInterestRoutes);
router.use("/corporate-risk", corporateRiskRoutes);
router.use("/client-risk", clientRiskRoutes);
router.use("/staff-sleep-disturbance", staffSleepDisturbanceRoutes);

export default router;
