enum UserErrorCode {
  TOKEN_REQUIRED = "TOKEN_REQUIRED",
  INVALID_TOKEN = "INVALID_TOKEN",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
  INVALID_PASSWORD_RESET_TOKEN = "INVALID_PASSWORD_RESET_TOKEN",
}

export default UserErrorCode;
