enum TimesheetErrorCode {
  TIMESHEET_NOT_FOUND = "TIMESHEET_NOT_FOUND",
  INVOICE_NOT_CREATED = "INVOICE_NOT_CREATED",
  FAILED_TO_GENERATE_INVOICE = "FAILED_TO_GENERATE_INVOICE",
}

export default TimesheetErrorCode;
