enum IntegrationErrorCode {
  INTEGRATION_NOT_FOUND = "INTEGRATION_NOT_FOUND",
  INTEGRATION_NOT_CREATED = "INTEGRATION_NOT_CREATED",
  INTEGRATION_ALREADY_EXISTS = "INTEGRATION_ALREADY_EXISTS",
}

export default IntegrationErrorCode;
