enum IntegrationErrorCode {
  INTEGRATION_EXTERNAL_DATA_NOT_FOUND = "INTEGRATION_EXTERNAL_DATA_NOT_FOUND",
  INTEGRATION_EXTERNAL_DATA_ALREADY_EXISTS = "INTEGRATION_EXTERNAL_DATA_ALREADY_EXISTS",
}

export default IntegrationErrorCode;
